# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

before_install:
  - sudo apt-get -y install libnlopt-dev

r_binary_packages: 
  - rstan

r:
- oldrel
- release
- devel

after_success:
  - Rscript -e 'covr::codecov()'

# circa 2018-03-01, devel takes 45m to build and causes timeout error

matrix:
  allow_failures:
    - r: devel

